### ISSUE TITLE
Problem with config

### ISSUE THREAD

**Issue by partyzant** [xiidea/ckeditor-easykeymap-plugin#2]
When I use `config.easykeymaps[CKEDITOR.ALT + 81] = String.fromCharCode(190);`
I get error: `Uncaught TypeError: Cannot set property '4456531' of undefined`.
So I wanted to use the second method of defining shortcuts, but how to get this 7 digit number to config certain shortcut?

**Comment by ronisaha** [comment]
Can you create a sample repository with a example code which is not working. to be able to use this library, first you have to [install the plugin](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_plugins.html). After that any one of the configuration will work. If you haven't install the plugin properly(It seems you haven't) None of the configuration will work.

### How to get the numbers?   
You can just `console.log(CKEDITOR.ALT + "Q".charCodeAt())` to get the number, If you have CKEDITOR installed.

**Comment by partyzant** [comment]
To install plugin I've put it inside plugin directory and add to my config file `config.extraPlugins = 'easykeymap';`, do I need to do something more?
Anyway this method works
`config.easykeymaps = {
        4456530 : String.fromCharCode(174),   //ALT + R
        4456515 : String.fromCharCode(169)   //ALT + C
    };`
as well as 'console.log(CKEDITOR.ALT + "Q".charCodeAt())', so thank you for your help.

**Comment by ronisaha** [comment]
Ok, I got it . I may have to update the documentation. 
 
BR
Roni
